#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code
# Must use awk
#You are not allowed to use while, for, until and cut

awk -F' ' ' {print $1, $9}' apache-access.log
