#!/usr/bin/env bash
# Bash script displays the time for 12 hours and 59 minutes
# Displays the hours from 0 to 12
# Displays minutes from 1 to 59
# Must use the while loop

hour=0
minute=1

while [ $hour -le 12 ]
do
	while [ $minute -le 59 ]
	do
		printf "%02d:%02d\n" $hour $minute
		minute=$((minute + 1))
	done
		minute=0
		hour=$((hour + 1))
done | head -n 70

