#!/usr/bin/env bash
# Bash script that accepts one argument
# script should run the whoami command under 
# the user passed as an argument
#  try your script by passing different users
sudo -u "$1" whoami
